---
- name: "Lamp-Role Demo"
  hosts: all
  become: true
  roles:
    - lamp

  tasks:
    - name: "Wordpress - Downloading Installation Files"
      get_url:
        url: "{{ wordpress_url }}"
        dest: /tmp/wordpress.tar.gz
      vars:
        wordpress_url: "https://wordpress.org/wordpress-4.8.tar.gz"
            
    - name: "Wordpress - Extracting Installation File"
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: true
    
    - name: "Worpress  - Copying Contents To DocumentRoot"
      copy:
        src: /tmp/wordpress/
        dest: "/var/www/html/{{ domain }}"
        remote_src: true
            
    - name: "Wordpress - Creating wp-config.php"
      template:
        src: wp-config.php.tmpl
        dest: "/var/www/html/{{ domain }}/wp-config.php"
        owner: "{{ httpd_owner }}"
        group: "{{ httpd_group }}"
    
    - name: "Post-Installation Clean-up"
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/wordpress/
        - /tmp/wordpress.tar.gz
        
    - name: "Post-Installation Restart"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - httpd
        - mariadb
